# Generated by Django 4.0.4 on 2022-04-26 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_birth_date_employee_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkedHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_hours', models.IntegerField()),
                ('worked_date', models.DateField(null=True)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
        ),
    ]
